"""Shared, dependency-free contracts for the HomeOps Fleet Deploy Lab."""

import importlib

from .deployment_spec import (
    COLORS,
    ENVIRONMENTS,
    FAILURE_MODES,
    IMPLEMENTATIONS,
    SCHEMA_VERSION,
    SHAPES,
    STRATEGIES,
    TARGETS_BY_ENVIRONMENT,
    DeploymentSpec,
    DeploymentSpecError,
    canonicalize_deployment_spec,
    expand_targets,
    validate_deployment_spec,
)
from .fleet_state import (
    DEFAULT_STATE_PATH,
    DEPLOYMENT_STATUSES,
    DISPATCH_STATUSES,
    STATE_PATH_ENV,
    STATE_SCHEMA_VERSION,
    VEHICLE_STATUSES,
    DeploymentAdmissionLimitError,
    DeploymentConflictError,
    DeploymentCooldownError,
    DeploymentState,
    DispatchClaimError,
    FleetProfile,
    FleetStateError,
    FleetStateStore,
    InvalidStateTransitionError,
    QueueResult,
    UnknownDeploymentError,
    UnknownTargetError,
    VehicleState,
)
from .github_dispatch import (
    DEFAULT_MANIFEST_BRANCH,
    DEFAULT_REPOSITORY,
    DEFAULT_WORKFLOW_FILE,
    GITHUB_REPOSITORY_ENV,
    GITHUB_TOKEN_ENV,
    MANIFEST_BRANCH_ENV,
    WORKFLOW_FILE_ENV,
    GitHubFleetClient,
    GitHubFleetConfigurationError,
    GitHubFleetError,
    ManifestCommitReceipt,
    ManifestConflictError,
    WorkflowDispatchReceipt,
)

_DEPLOYER_EXPORTS = frozenset(
    {
        "API_BASE_URL_ENV",
        "API_KEY_ENV",
        "ArtifactIdentityError",
        "DeploymentApi",
        "DeploymentArtifact",
        "DeploymentEvent",
        "DeploymentEventType",
        "DeploymentResult",
        "DeploymentVerificationError",
        "DeployerError",
        "FleetApiClient",
        "FleetApiError",
        "FleetDeployer",
        "ProfileArtifact",
        "PythonDeployer",
        "deploy",
    }
)


def __getattr__(name: str):
    """Load deployer exports only when imported directly by a caller."""
    if name not in _DEPLOYER_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(".deployer", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


__all__ = [
    "COLORS",
    "ENVIRONMENTS",
    "FAILURE_MODES",
    "IMPLEMENTATIONS",
    "SCHEMA_VERSION",
    "SHAPES",
    "STRATEGIES",
    "TARGETS_BY_ENVIRONMENT",
    "DeploymentSpec",
    "DeploymentSpecError",
    "canonicalize_deployment_spec",
    "expand_targets",
    "validate_deployment_spec",
    "DEFAULT_STATE_PATH",
    "DEPLOYMENT_STATUSES",
    "DISPATCH_STATUSES",
    "STATE_PATH_ENV",
    "STATE_SCHEMA_VERSION",
    "VEHICLE_STATUSES",
    "DeploymentAdmissionLimitError",
    "DeploymentConflictError",
    "DeploymentCooldownError",
    "DeploymentState",
    "DispatchClaimError",
    "FleetProfile",
    "FleetStateError",
    "FleetStateStore",
    "InvalidStateTransitionError",
    "QueueResult",
    "UnknownDeploymentError",
    "UnknownTargetError",
    "VehicleState",
    "DEFAULT_MANIFEST_BRANCH",
    "DEFAULT_REPOSITORY",
    "DEFAULT_WORKFLOW_FILE",
    "GITHUB_REPOSITORY_ENV",
    "GITHUB_TOKEN_ENV",
    "MANIFEST_BRANCH_ENV",
    "WORKFLOW_FILE_ENV",
    "GitHubFleetClient",
    "GitHubFleetConfigurationError",
    "GitHubFleetError",
    "ManifestCommitReceipt",
    "ManifestConflictError",
    "WorkflowDispatchReceipt",
    "API_BASE_URL_ENV",
    "API_KEY_ENV",
    "ArtifactIdentityError",
    "DeploymentApi",
    "DeploymentArtifact",
    "DeploymentEvent",
    "DeploymentEventType",
    "DeploymentResult",
    "DeploymentVerificationError",
    "DeployerError",
    "FleetApiClient",
    "FleetApiError",
    "FleetDeployer",
    "ProfileArtifact",
    "PythonDeployer",
    "deploy",
]
