"""Shared, dependency-free contracts for the HomeOps Fleet Deploy Lab."""

from .deployment_spec import (
    COLORS,
    ENVIRONMENTS,
    FAILURE_MODES,
    IMPLEMENTATIONS,
    SCHEMA_VERSION,
    SHAPES,
    STRATEGIES,
    TARGETS_BY_ENVIRONMENT,
    DeploymentSpec,
    DeploymentSpecError,
    canonicalize_deployment_spec,
    expand_targets,
    validate_deployment_spec,
)
from .fleet_state import (
    DEFAULT_STATE_PATH,
    DEPLOYMENT_STATUSES,
    STATE_PATH_ENV,
    STATE_SCHEMA_VERSION,
    VEHICLE_STATUSES,
    DeploymentConflictError,
    DeploymentState,
    FleetProfile,
    FleetStateError,
    FleetStateStore,
    InvalidStateTransitionError,
    QueueResult,
    UnknownDeploymentError,
    UnknownTargetError,
    VehicleState,
)

__all__ = [
    "COLORS",
    "ENVIRONMENTS",
    "FAILURE_MODES",
    "IMPLEMENTATIONS",
    "SCHEMA_VERSION",
    "SHAPES",
    "STRATEGIES",
    "TARGETS_BY_ENVIRONMENT",
    "DeploymentSpec",
    "DeploymentSpecError",
    "canonicalize_deployment_spec",
    "expand_targets",
    "validate_deployment_spec",
    "DEFAULT_STATE_PATH",
    "DEPLOYMENT_STATUSES",
    "STATE_PATH_ENV",
    "STATE_SCHEMA_VERSION",
    "VEHICLE_STATUSES",
    "DeploymentConflictError",
    "DeploymentState",
    "FleetProfile",
    "FleetStateError",
    "FleetStateStore",
    "InvalidStateTransitionError",
    "QueueResult",
    "UnknownDeploymentError",
    "UnknownTargetError",
    "VehicleState",
]
